---
title: "Numbers and Percentages"
output: html_fragment
---

# Numbers and Percentages
### Data Sources
All data was sourced from the Australian Bureau of Statistics (ABS) [Census of Population of Housing](https://www.abs.gov.au/census) [Application Programming Interface (API)](https://www.abs.gov.au/about/data-services/application-programming-interfaces-apis/data-api-user-guide). Specifically, [long term health conditions](https://www.abs.gov.au/articles/long-term-health-conditions) were available only for 2021, while [core activity need for assistance](https://www.abs.gov.au/census/guide-census-data/census-dictionary/2021/variables-topic/disability-and-carers/core-activity-need-assistance-assnp) was available for the full data series. 

2021 [Australian Statistical Geography Standard (ASGS)](https://www.abs.gov.au/statistics/statistical-geography/australian-statistical-geography-standard-asgs) areas were used for all boundaries, visualised at the [Statisical Area 2 (SA2)](https://www.abs.gov.au/statistics/standards/australian-statistical-geography-standard-asgs-edition-3/jul2021-jun2026/main-structure-and-greater-capital-city-statistical-areas) level. That is, while historical data is visualised for 2011 and 2016, these have been populated according to the updated 2021 ASGS boundaries in the time series tables. 


### Included variables
The variables chosen for estimation were those included in the time series tables provided by the ABS, which have historically been of interest to the Sydney Local Health District. This is not exhaustive, and there are many additional variables included in the time series tables (and, indeed, the entire Census questionnaire), but it was decided to focus on a smaller set of variables in the interest of usability and relevance. These included

- [Usual resident population](https://www.abs.gov.au/statistics/people/population/population-census/latest-release), reflecting the count on Census night by area of usual residence
- Proportion born overseas, calculated using the [Country of Birth](https://www.abs.gov.au/census/guide-census-data/census-dictionary/2021/variables-topic/cultural-diversity/country-birth-person-bplp) census variable
- Proportion of people primarily speaking a language other than English at home, calculated using the [Language used at Home](https://www.abs.gov.au/census/guide-census-data/census-dictionary/2021/variables-topic/cultural-diversity/language-used-home-lanp) census variable
- Median personal income, calculated using the [household income](https://www.abs.gov.au/census/guide-census-data/census-dictionary/2021/variables-topic/income-and-work/total-household-income-weekly-hind) census variable

### Method
In the case of usual resident populations and median personal income, both variables were pre-calculated by the ABS, and so were used as is. For both proportion variables, total valid responses were used as the denominators, with any missing or invalid responses excluded from the total. For example, proportion born overseas is the number of people who listed a country of birth other than Australia, divided by the number of people people who listed *any* country of birth, with those with missing or invalid responses excluded. 


### Limitations
Usual resident populations are known to [undercount certain population](https://www.abs.gov.au/statistics/people/population/2021-census-overcount-and-undercount/latest-release) groups, and thus the population estimates used are subject to some bias. While this may be small overall, it is likely to be especially pronounced in areas with higher populations of demographic groups known to be undercounted. This should be considered when interpreting estimates.

Income data reported in the census are self-reported, with no validation or cross reference to taxation and/or administrative data. There is the possibility that this estimate may be biased and there has been no correction for this. Though this bias is likely to be relatively small when aggregated, and especially when only reporting medians, it should be considered when interpreting estimates.

The exclusion of invalid responses from the denominators in the proportions of those born overseas and those speaking a language other than English at home may bias estimates slightly. That is, those born overseas are slightly more likely to be [undercounted](https://www.abs.gov.au/statistics/people/population/2021-census-overcount-and-undercount/latest-release), and this is likely to affect overall estimates. Estimates produced here should thus be taken as *indicative* of population distributions, rather than objective truth.




